version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

parameters:
  some_unrelated_parameter:
    type: boolean
    default: false

jobs:
  run-generated-config:
    executor: continuation/default
    steps:
      - continuation/run:
          configuration-path: .circleci/generated-config.yml
          pipeline-parameters-json-file: .circleci/generated-config-parameters.json

workflows:
  setup:
    jobs:
      - run-generated-config
