version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

parameters:
  some_unrelated_parameter:
    type: string
    default: 'using default'

jobs:
  run-generated-config:
    executor: continuation/default
    resource_class: small
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/generated-config.yml
          parameters: .circleci/generated-config-parameters.json

workflows:
  setup:
    jobs:
      - run-generated-config
