version: 2.1

parameters:
  some_unrelated_parameter:
    type: string
    default: 'using default'

  foo:
    type: integer

  bar:
    type: integer
    default: 0

  baz:
    type: integer
    default: 0

  qux:
    type: integer
    default: 0

jobs:
  print-parameters:
    docker:
      - image: cimg/ruby:3.2.2
    resource_class: small
    steps:
      - run:
          name: Print parameters
          command: |
            echo "some_unrelated_parameter: << pipeline.parameters.some_unrelated_parameter >>"
            echo "foo: << pipeline.parameters.foo >>"
            echo "bar: << pipeline.parameters.bar >>"
            echo "baz: << pipeline.parameters.baz >>"
            echo "qux: << pipeline.parameters.qux >>"

workflows:
  main:
    jobs:
      - print-parameters
